# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e979bb8d0ef61183762789185be8a2aa53ddfd01bd5bdef5cff051ad8baca722405220cd0831f58970b29211cbdc3ad238f1c7ddc6d2684fe4f33247d3e18ad5

test:
  secret_key_base: 52e6dbce90e6dc333c055b8cf618dfeb596e868138856b6f197e3e9caf587d62a7c8d4857566532dec264e5713d65453bbd381d572bbfd633fc650a767df23ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
